<?php

/**
 * Pet held item id => display metadata (Hypixel pet item IDs).
 */
return [
    'PET_ITEM_ALL_SKILLS_BOOST_COMMON' => ['name' => 'All Skills Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_BIG_TEETH_COMMON' => ['name' => 'Big Teeth', 'tier' => 'COMMON'],
    'PET_ITEM_IRON_CLAWS_COMMON' => ['name' => 'Iron Claws', 'tier' => 'COMMON'],
    'PET_ITEM_SHARPENED_CLAWS_UNCOMMON' => ['name' => 'Sharpened Claws', 'tier' => 'UNCOMMON'],
    'PET_ITEM_HARDENED_SCALES_UNCOMMON' => ['name' => 'Hardened Scales', 'tier' => 'UNCOMMON'],
    'PET_ITEM_BUBBLEGUM' => ['name' => 'Bubblegum', 'tier' => 'RARE'],
    'PET_ITEM_LUCKY_CLOVER' => ['name' => 'Lucky Clover', 'tier' => 'EPIC'],
    'PET_ITEM_TEXTBOOK' => ['name' => 'Textbook', 'tier' => 'LEGENDARY'],
    'PET_ITEM_SADDLE' => ['name' => 'Saddle', 'tier' => 'UNCOMMON'],
    'PET_ITEM_EXP_SHARE' => ['name' => 'Exp Share', 'tier' => 'EPIC'],
    'PET_ITEM_TIER_BOOST' => ['name' => 'Tier Boost', 'tier' => 'LEGENDARY'],
    'PET_ITEM_COMBAT_SKILL_BOOST_COMMON' => ['name' => 'Combat Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_COMBAT_SKILL_BOOST_UNCOMMON' => ['name' => 'Combat Exp Boost', 'tier' => 'UNCOMMON'],
    'PET_ITEM_COMBAT_SKILL_BOOST_RARE' => ['name' => 'Combat Exp Boost', 'tier' => 'RARE'],
    'PET_ITEM_COMBAT_SKILL_BOOST_EPIC' => ['name' => 'Combat Exp Boost', 'tier' => 'EPIC'],
    'PET_ITEM_FISHING_SKILL_BOOST_COMMON' => ['name' => 'Fishing Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_FISHING_SKILL_BOOST_UNCOMMON' => ['name' => 'Fishing Exp Boost', 'tier' => 'UNCOMMON'],
    'PET_ITEM_FISHING_SKILL_BOOST_RARE' => ['name' => 'Fishing Exp Boost', 'tier' => 'RARE'],
    'PET_ITEM_FISHING_SKILL_BOOST_EPIC' => ['name' => 'Fishing Exp Boost', 'tier' => 'EPIC'],
    'PET_ITEM_MINING_SKILL_BOOST_COMMON' => ['name' => 'Mining Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_MINING_SKILL_BOOST_UNCOMMON' => ['name' => 'Mining Exp Boost', 'tier' => 'UNCOMMON'],
    'PET_ITEM_MINING_SKILL_BOOST_RARE' => ['name' => 'Mining Exp Boost', 'tier' => 'RARE'],
    'PET_ITEM_MINING_SKILL_BOOST_EPIC' => ['name' => 'Mining Exp Boost', 'tier' => 'EPIC'],
    'PET_ITEM_FORAGING_SKILL_BOOST_COMMON' => ['name' => 'Foraging Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_FORAGING_SKILL_BOOST_UNCOMMON' => ['name' => 'Foraging Exp Boost', 'tier' => 'UNCOMMON'],
    'PET_ITEM_FORAGING_SKILL_BOOST_RARE' => ['name' => 'Foraging Exp Boost', 'tier' => 'RARE'],
    'PET_ITEM_FORAGING_SKILL_BOOST_EPIC' => ['name' => 'Foraging Exp Boost', 'tier' => 'EPIC'],
    'PET_ITEM_FARMING_SKILL_BOOST_COMMON' => ['name' => 'Farming Exp Boost', 'tier' => 'COMMON'],
    'PET_ITEM_FARMING_SKILL_BOOST_UNCOMMON' => ['name' => 'Farming Exp Boost', 'tier' => 'UNCOMMON'],
    'PET_ITEM_FARMING_SKILL_BOOST_RARE' => ['name' => 'Farming Exp Boost', 'tier' => 'RARE'],
    'PET_ITEM_FARMING_SKILL_BOOST_EPIC' => ['name' => 'Farming Exp Boost', 'tier' => 'EPIC'],
    'PET_ITEM_SPOOKY_CUPCAKE' => ['name' => 'Spooky Cupcake', 'tier' => 'UNCOMMON'],
    'MINOS_RELIC' => ['name' => 'Minos Relic', 'tier' => 'EPIC'],
    'DWARF_TURTLE_SHELMET' => ['name' => 'Dwarf Turtle Shelmet', 'tier' => 'RARE'],
    'PET_ITEM_QUICK_CLAW' => ['name' => 'Quick Claw', 'tier' => 'EPIC'],
    'ANTIQUE_REMEDIES' => ['name' => 'Antique Remedies', 'tier' => 'EPIC'],
    'CROCHET_TIGER_PLUSHIE' => ['name' => 'Crochet Tiger Plushie', 'tier' => 'EPIC'],
    'REAPER_GEM' => ['name' => 'Reaper Gem', 'tier' => 'LEGENDARY'],
    'PET_ITEM_FLYING_PIG' => ['name' => 'Flying Pig', 'tier' => 'UNCOMMON'],
    'GREEN_BANDANA' => ['name' => 'Green Bandana', 'tier' => 'LEGENDARY'],
];
